pythia_models:
  - name: "EleutherAI/pythia-70m"
  - name: "EleutherAI/pythia-160m"
    revision: "step1"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step10000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step20000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step30000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step40000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step50000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step60000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step70000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step80000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step90000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step100000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step110000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step120000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step130000"
  # - name: "EleutherAI/pythia-160m"
  #   revision: "step140000"
  # - name: "EleutherAI/pythia-160m"
  # - name: "EleutherAI/pythia-410m"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step1"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step10000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step20000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step30000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step40000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step50000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step60000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step70000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step80000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step90000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step100000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step110000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step120000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step130000"
  # - name: "EleutherAI/pythia-1b"
  #   revision: "step140000"
  # - name: "EleutherAI/pythia-1b"
  # - name: "EleutherAI/pythia-1.4b"
  # - name: "EleutherAI/pythia-2.8b"
  # - name: "EleutherAI/pythia-6.9b"
  # - name: "EleutherAI/pythia-12b"
  # - name: "EleutherAI/pythia-70m-deduped"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step1"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step10000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step20000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step30000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step40000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step50000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step60000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step70000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step80000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step90000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step100000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step110000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step120000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step130000"
  # - name: "EleutherAI/pythia-160m-deduped"
  #   revision: "step140000"
  # - name: "EleutherAI/pythia-160m-deduped"
  # - name: "EleutherAI/pythia-410m-deduped"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step1"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step10000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step20000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step30000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step40000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step50000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step60000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step70000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step80000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step90000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step100000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step110000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step120000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step130000"
  # - name: "EleutherAI/pythia-1b-deduped"
  #   revision: "step140000"
  # - name: "EleutherAI/pythia-1b-deduped"
  # - name: "EleutherAI/pythia-1.4b-deduped"
  # - name: "EleutherAI/pythia-2.8b-deduped"
  # - name: "EleutherAI/pythia-6.9b-deduped"
  # - name: "EleutherAI/pythia-12b-deduped"

ud_corpora:
  - {lang: "en", genre: "EWT", split: "train"}
  - {lang: "zh", genre: "GSDSimp", split: "train"}

batch_size: 1